# Generated by Django 4.0.1 on 2022-02-10 10:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 10, 26, 25, 224601, tzinfo=utc)),
        ),
    ]
